### PR TITLE
Added customizability for animation and fade durations

### PR DESCRIPTION
**Pull request by kylerjensen**
We love using this library, but we needed the ability to control the animation and fade durations. All changes in this pull request should be backwards-compatible.

### CODE REVIEW

**Comment by Kjens93** [comment]
All changes in this pull request should be backwards-compatible.

**Comment by kylerjensen** [comment]
@ykyouhei, can you merge this PR and release a new version please? Thank you!

**Comment by kylerjensen** [comment]
@ykyouhei are there any issues with this PR?

**Comment by kylerjensen** [comment]
Closing this PR because the repository maintainer did not respond.

**Pull request closed without merging**
